version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: cobranzas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cobranzas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Abc123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    networks:
      - app-network
    ports:
      - "8080:8080"

  frontend:
    build: 
      context: ./from
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8081:80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
